# Generated by Django 6.0.4 on 2026-05-26 19:34

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utilisateur_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', accounts.models.UtilisateurManager()),
            ],
        ),
    ]
