# Generated by Django 6.0.4 on 2026-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
