# Generated by Django 6.0.4 on 2026-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_contactmessage_reponse_contactmessage_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message de contact'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification'},
        ),
        migrations.AlterModelOptions(
            name='plat',
            options={'verbose_name': 'Plat'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant'},
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.PositiveSmallIntegerField(default=5, help_text='Note sur 5 étoiles.'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='reponse',
            field=models.TextField(blank=True, help_text="Champ rempli par l'administrateur lors de la réponse.", null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url_redirection',
            field=models.CharField(help_text='Lien frontend (ex: /orderhistory).', max_length=255),
        ),
        migrations.AlterField(
            model_name='plat',
            name='categorie',
            field=models.CharField(help_text='Ex: Entrées, Plats de résistance...', max_length=100),
        ),
        migrations.AlterField(
            model_name='plat',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Permet de masquer un plat temporairement (rupture).'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='prix',
            field=models.DecimalField(decimal_places=3, help_text='Prix unitaire.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='horaires',
            field=models.CharField(blank=True, help_text='Ex: 11h-23h non stop', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(blank=True, help_text="URL de l'image de couverture.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='nom',
            field=models.CharField(help_text='Nom commercial du restaurant.', max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculée à partir des avis.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='temps_livraison_estime',
            field=models.IntegerField(help_text='Durée moyenne de livraison en minutes.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type_cuisine',
            field=models.CharField(help_text='Ex: Italienne, Sushi, Burger...', max_length=100),
        ),
    ]
