# Generated by Django 6.0.4 on 2026-05-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='telephone_paiement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
