# Generated by Django 6.0.4 on 2026-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_commande_telephone_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
